/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package de.tomsplayground.peanuts.calculator;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int NUMBER = 4;
	/** RegularExpression Id. */
	int DIGIT = 5;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "<NUMBER>", "<DIGIT>", "\"+\"", "\"-\"", "\"*\"",
			"\"/\"", "\"(\"", "\")\"", };

}
